spring.application.name=fx-catalog-service
server.port=8002
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

# Resilience4j Circuit Breaker (instance name must match @CircuitBreaker name = "courseService")
resilience4j.circuitbreaker.instances.courseService.register-health-indicator=true
resilience4j.circuitbreaker.instances.courseService.sliding-window-size=10
resilience4j.circuitbreaker.instances.courseService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.courseService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.courseService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.courseService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.courseService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.courseService.event-consumer-buffer-size=10

# Actuator (opcional taller): salud y circuit breakers
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
