spring.application.name=fx-catalog-service
server.port=8002
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

# Hystrix settings (global defaults)
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=2000
hystrix.command.default.circuitBreaker.requestVolumeThreshold=5
hystrix.command.default.circuitBreaker.errorThresholdPercentage=50
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds=5000
hystrix.command.default.metrics.rollingStats.timeInMilliseconds=10000